/* The following code was generated by JFlex 1.4.1 on 19/12/18 22:14 */

/*
 * Generated on 12/19/18 10:14 PM
 */
package org.openflexo.fml.controller.view;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class FMLTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 3;
  public static final int DOCCOMMENT = 2;
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\20\1\10\1\0\1\20\1\16\22\0\1\20\1\32\1\15"+
    "\1\17\1\1\1\36\1\34\1\7\2\33\1\22\1\35\1\30\1\26"+
    "\1\24\1\21\1\4\3\6\4\6\2\3\1\46\1\30\1\66\1\65"+
    "\1\67\1\32\1\31\1\57\2\5\1\60\2\5\2\1\1\63\10\1"+
    "\1\62\2\1\1\61\1\64\4\1\1\33\1\11\1\33\1\70\1\2"+
    "\1\0\1\50\1\14\1\51\1\54\1\25\1\43\1\1\1\37\1\44"+
    "\2\1\1\45\1\55\1\53\1\52\1\41\1\1\1\13\1\42\1\40"+
    "\1\12\1\56\1\47\1\23\2\1\1\27\1\71\1\27\1\32\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\2\1\2\2\1\3\1\1\1\4\1\5\2\6"+
    "\2\1\1\6\1\7\1\1\3\6\10\1\3\6\1\10"+
    "\1\11\4\10\1\12\5\10\1\13\3\10\1\0\1\14"+
    "\1\0\2\14\1\1\2\4\1\15\1\16\1\17\1\20"+
    "\1\1\4\0\4\1\1\21\6\1\1\22\4\0\1\23"+
    "\11\0\1\20\1\0\1\24\1\4\1\25\1\4\1\26"+
    "\1\1\4\0\13\1\15\0\1\4\1\1\2\0\1\27"+
    "\1\0\3\1\1\30\5\1\1\27\2\0\1\31\2\0"+
    "\1\32\2\0\1\33\1\0\1\4\1\1\3\0\6\1"+
    "\7\0\1\4\1\1\3\0\2\1\2\0\1\34\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\350\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c"+
    "\0\u0366\0\350\0\u03a0\0\350\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658"+
    "\0\u0692\0\u06cc\0\350\0\u0706\0\u0740\0\u077a\0\u07b4\0\350"+
    "\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6\0\350\0\u0910\0\u094a"+
    "\0\u0984\0\u09be\0\u09f8\0\u02f2\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\350\0\350\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c"+
    "\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0122\0\u0dd2"+
    "\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\350\0\u0f2e\0\u0f68"+
    "\0\u0fa2\0\u0fdc\0\350\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe"+
    "\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u0a6c\0\u1294"+
    "\0\350\0\u12ce\0\350\0\u1308\0\u1342\0\u137c\0\u13b6\0\u13f0"+
    "\0\u142a\0\u1464\0\u149e\0\u14d8\0\u1512\0\u154c\0\u1586\0\u15c0"+
    "\0\u15fa\0\u1634\0\u166e\0\u16a8\0\u16e2\0\u171c\0\u1756\0\u1790"+
    "\0\u17ca\0\u1804\0\u183e\0\u1878\0\u18b2\0\u18ec\0\u1926\0\u1960"+
    "\0\u199a\0\u19d4\0\u1a0e\0\u1a48\0\350\0\u1a82\0\u1abc\0\u1af6"+
    "\0\u1b30\0\u0122\0\u1b6a\0\u1ba4\0\u1bde\0\u1c18\0\u1c52\0\u0122"+
    "\0\u1c8c\0\u1cc6\0\u1d00\0\u1d3a\0\u1d74\0\u1dae\0\u1de8\0\u1e22"+
    "\0\u1e5c\0\u1e96\0\u1ed0\0\u1f0a\0\u1f44\0\u1f7e\0\u1fb8\0\u1ff2"+
    "\0\u202c\0\u2066\0\u20a0\0\u20da\0\u2114\0\u214e\0\u1d00\0\u2188"+
    "\0\u1dae\0\u21c2\0\u1e5c\0\u21fc\0\u2236\0\u2270\0\u22aa\0\u22e4"+
    "\0\u231e\0\u2358\0\u2392\0\u23cc\0\u2406\0\350\0\u2440";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\7\1\10\1\6\1\7\1\5\1\11"+
    "\1\5\1\12\2\6\1\13\2\5\1\14\1\15\1\16"+
    "\1\6\1\17\1\20\1\21\1\22\1\5\1\23\1\24"+
    "\1\22\1\25\1\26\1\16\2\6\1\27\2\6\1\30"+
    "\1\6\1\24\1\31\1\32\1\33\2\6\1\34\1\35"+
    "\1\36\6\6\1\16\1\37\1\40\1\24\1\41\10\42"+
    "\1\43\11\42\1\44\14\42\1\45\3\42\1\46\3\42"+
    "\1\47\32\42\1\50\11\42\1\51\14\42\1\52\3\42"+
    "\1\53\3\42\1\54\22\42\10\55\1\56\26\55\1\57"+
    "\3\55\1\60\3\55\1\61\22\55\73\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\7\6"+
    "\1\0\16\6\5\0\3\63\2\7\1\63\1\7\2\0"+
    "\4\63\2\0\1\63\3\0\1\63\1\64\1\65\3\0"+
    "\1\63\5\0\7\63\1\0\16\63\5\0\3\63\2\7"+
    "\1\63\1\7\2\0\4\63\2\0\1\63\3\0\1\66"+
    "\1\64\1\65\3\0\1\63\5\0\7\63\1\0\16\63"+
    "\6\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\3\6\1\67\3\6\1\0\16\6\5\0"+
    "\10\13\1\70\1\71\3\13\1\72\54\13\20\0\1\14"+
    "\72\0\1\73\1\74\42\0\1\24\71\0\1\24\7\0"+
    "\2\75\1\0\1\75\64\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\76\1\0\1\6\11\0\7\6\1\0\16\6"+
    "\33\0\1\24\36\0\1\24\63\0\1\77\1\100\1\101"+
    "\2\0\1\102\41\0\1\24\72\0\1\24\27\0\1\24"+
    "\5\0\6\6\2\0\1\62\1\103\1\104\1\6\6\0"+
    "\1\6\1\0\1\6\11\0\7\6\1\0\16\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\7\6\1\0\6\6\1\105\7\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\5\6\1\106\1\6\1\0\16\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\3\6"+
    "\1\107\3\6\1\0\2\6\1\110\13\6\6\0\6\6"+
    "\2\0\1\62\1\6\1\111\1\6\6\0\1\6\1\0"+
    "\1\6\11\0\7\6\1\0\3\6\1\112\12\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\113"+
    "\11\0\7\6\1\0\16\6\6\0\6\6\2\0\1\62"+
    "\3\6\6\0\1\6\1\0\1\6\11\0\7\6\1\0"+
    "\3\6\1\114\12\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\7\6\1\0\3\6"+
    "\1\115\12\6\73\0\1\16\72\0\1\16\73\0\1\24"+
    "\10\42\1\0\11\42\1\0\14\42\1\0\3\42\1\0"+
    "\3\42\1\0\22\42\21\0\1\116\110\0\1\117\71\0"+
    "\1\120\3\0\1\121\74\0\1\122\43\0\1\123\110\0"+
    "\1\124\71\0\1\125\3\0\1\126\74\0\1\127\22\0"+
    "\10\55\1\0\26\55\1\0\3\55\1\0\3\55\1\0"+
    "\22\55\40\0\1\130\71\0\1\131\3\0\1\132\74\0"+
    "\1\133\34\0\1\134\57\0\7\63\2\0\4\63\2\0"+
    "\1\63\3\0\1\63\1\0\1\63\3\0\1\63\5\0"+
    "\7\63\1\0\16\63\5\0\3\63\2\135\1\63\1\135"+
    "\2\0\4\63\2\0\1\63\3\0\1\63\1\0\1\63"+
    "\1\136\2\0\1\63\3\0\1\136\1\0\7\63\1\0"+
    "\16\63\5\0\3\63\4\137\2\0\3\63\1\137\2\0"+
    "\1\63\3\0\1\63\1\0\1\137\3\0\1\63\5\0"+
    "\4\63\1\137\2\63\1\0\1\63\2\137\2\63\1\137"+
    "\2\63\2\137\4\63\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\107\11\0\7\6\1\0\16\6"+
    "\5\0\11\70\1\140\3\70\1\141\60\70\1\13\1\70"+
    "\2\13\1\0\1\13\1\142\3\13\22\70\1\13\2\70"+
    "\1\13\7\70\1\13\16\70\22\0\1\143\47\0\3\63"+
    "\2\75\1\63\1\75\2\0\4\63\2\0\1\63\3\0"+
    "\1\63\1\0\1\65\3\0\1\63\5\0\7\63\1\0"+
    "\16\63\6\0\6\6\2\0\1\62\3\6\6\0\1\6"+
    "\1\0\1\6\11\0\1\6\1\144\5\6\1\0\16\6"+
    "\17\0\1\145\104\0\1\146\126\0\1\147\34\0\1\150"+
    "\45\0\6\6\2\0\1\62\2\6\1\151\6\0\1\6"+
    "\1\0\1\6\11\0\7\6\1\0\16\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\5\6\1\152\1\6\1\0\16\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\2\6"+
    "\1\153\4\6\1\0\16\6\6\0\6\6\2\0\1\62"+
    "\3\6\6\0\1\6\1\0\1\6\11\0\1\6\1\154"+
    "\5\6\1\0\16\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\1\6\1\155\5\6"+
    "\1\0\16\6\6\0\6\6\2\0\1\62\3\6\6\0"+
    "\1\6\1\0\1\156\11\0\7\6\1\0\16\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\7\6\1\0\4\6\1\157\11\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\4\6\1\160\1\6\1\161\1\0\16\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\7\6\1\0\5\6\1\162\10\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\5\6"+
    "\1\163\1\6\1\0\16\6\45\0\1\164\72\0\1\165"+
    "\75\0\1\166\73\0\1\167\62\0\1\170\72\0\1\171"+
    "\75\0\1\172\73\0\1\173\62\0\1\174\72\0\1\175"+
    "\75\0\1\176\73\0\1\177\25\0\4\200\5\0\1\200"+
    "\10\0\1\200\15\0\1\200\4\0\2\200\2\0\1\200"+
    "\2\0\2\200\11\0\3\63\2\135\1\63\1\135\2\0"+
    "\4\63\2\0\1\63\3\0\1\63\1\0\1\63\3\0"+
    "\1\63\5\0\7\63\1\0\16\63\10\0\2\135\1\0"+
    "\1\135\63\0\10\70\1\0\64\70\4\201\2\70\1\140"+
    "\2\70\1\201\1\141\7\70\1\201\15\70\1\201\4\70"+
    "\2\201\2\70\1\201\2\70\2\201\11\70\1\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\202\11\0"+
    "\7\6\1\0\16\6\45\0\1\203\73\0\1\204\112\0"+
    "\1\205\21\0\1\206\57\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\6\6\1\207\1\0"+
    "\16\6\6\0\6\6\2\0\1\62\3\6\6\0\1\6"+
    "\1\0\1\6\11\0\7\6\1\0\7\6\1\210\6\6"+
    "\6\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\7\6\1\0\3\6\1\211\12\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\1\212\6\6\1\0\16\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\5\6"+
    "\1\213\1\6\1\0\16\6\6\0\6\6\2\0\1\62"+
    "\3\6\6\0\1\6\1\0\1\6\11\0\7\6\1\0"+
    "\1\6\1\214\14\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\7\6\1\0\2\6"+
    "\1\215\13\6\6\0\6\6\2\0\1\62\3\6\6\0"+
    "\1\6\1\0\1\6\11\0\5\6\1\216\1\6\1\0"+
    "\16\6\6\0\6\6\2\0\1\62\3\6\6\0\1\6"+
    "\1\0\1\214\11\0\7\6\1\0\16\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\217\11\0"+
    "\7\6\1\0\16\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\7\6\1\0\5\6"+
    "\1\220\10\6\46\0\1\221\76\0\1\222\50\0\1\165"+
    "\70\0\1\223\106\0\1\224\76\0\1\225\50\0\1\171"+
    "\70\0\1\226\106\0\1\227\76\0\1\230\50\0\1\175"+
    "\70\0\1\231\50\0\4\232\5\0\1\232\10\0\1\232"+
    "\15\0\1\232\4\0\2\232\2\0\1\232\2\0\2\232"+
    "\11\0\3\70\4\233\2\70\1\140\2\70\1\233\1\141"+
    "\7\70\1\233\15\70\1\233\4\70\2\233\2\70\1\233"+
    "\2\70\2\233\11\70\1\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\6\11\0\7\6\1\0\4\6"+
    "\1\234\11\6\44\0\1\235\103\0\1\236\62\0\1\237"+
    "\30\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\5\6\1\240\1\6\1\0\16\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\7\6\1\0\1\6\1\241\14\6\6\0\6\6"+
    "\2\0\1\62\1\6\1\242\1\6\6\0\1\6\1\0"+
    "\1\6\11\0\7\6\1\0\16\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\7\6"+
    "\1\0\3\6\1\243\12\6\6\0\6\6\2\0\1\62"+
    "\3\6\6\0\1\6\1\0\1\6\11\0\1\6\1\244"+
    "\5\6\1\0\16\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\245\11\0\7\6\1\0\16\6"+
    "\6\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\7\6\1\0\4\6\1\67\11\6\6\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\6\6\1\107\1\0\16\6\47\0\1\165\3\0"+
    "\1\222\44\0\1\246\51\0\1\223\1\247\4\223\1\247"+
    "\2\0\3\223\2\0\1\247\1\0\1\223\1\247\1\223"+
    "\1\247\1\223\1\247\1\0\7\247\7\223\1\247\16\223"+
    "\1\247\46\0\1\171\3\0\1\225\44\0\1\250\51\0"+
    "\1\226\1\251\4\226\1\251\2\0\3\226\2\0\1\251"+
    "\1\0\1\226\1\251\1\226\1\251\1\226\1\251\1\0"+
    "\7\251\7\226\1\251\16\226\1\251\46\0\1\175\3\0"+
    "\1\230\44\0\1\252\51\0\1\231\1\253\4\231\1\253"+
    "\2\0\3\231\2\0\1\253\1\0\1\231\1\253\1\231"+
    "\1\253\1\231\1\253\1\0\7\253\7\231\1\253\16\231"+
    "\1\253\7\0\4\254\5\0\1\254\10\0\1\254\15\0"+
    "\1\254\4\0\2\254\2\0\1\254\2\0\2\254\11\0"+
    "\3\70\4\255\2\70\1\140\2\70\1\255\1\141\7\70"+
    "\1\255\15\70\1\255\4\70\2\255\2\70\1\255\2\70"+
    "\2\255\11\70\1\0\6\6\2\0\1\62\3\6\6\0"+
    "\1\6\1\0\1\6\11\0\7\6\1\0\5\6\1\256"+
    "\10\6\57\0\1\257\32\0\1\260\122\0\1\261\26\0"+
    "\6\6\2\0\1\62\3\6\6\0\1\6\1\0\1\6"+
    "\11\0\7\6\1\0\2\6\1\212\13\6\6\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\1\6\1\262\5\6\1\0\16\6\6\0\6\6\2\0"+
    "\1\62\3\6\6\0\1\6\1\0\1\6\11\0\1\6"+
    "\1\107\5\6\1\0\16\6\6\0\6\6\2\0\1\62"+
    "\3\6\6\0\1\6\1\0\1\6\11\0\7\6\1\0"+
    "\4\6\1\263\11\6\6\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\263\11\0\7\6\1\0\16\6"+
    "\6\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\2\6\1\242\4\6\1\0\16\6\26\0"+
    "\1\223\71\0\1\226\71\0\1\231\53\0\4\6\5\0"+
    "\1\6\10\0\1\6\15\0\1\6\4\0\2\6\2\0"+
    "\1\6\2\0\2\6\11\0\3\70\4\13\2\70\1\140"+
    "\2\70\1\13\1\141\7\70\1\13\15\70\1\13\4\70"+
    "\2\13\2\70\1\13\2\70\2\13\11\70\1\0\6\6"+
    "\2\0\1\62\3\6\6\0\1\6\1\0\1\6\11\0"+
    "\3\6\1\107\3\6\1\0\16\6\20\0\1\205\122\0"+
    "\1\264\77\0\1\265\20\0\6\6\2\0\1\62\3\6"+
    "\6\0\1\6\1\0\1\212\11\0\7\6\1\0\16\6"+
    "\6\0\6\6\2\0\1\62\3\6\6\0\1\6\1\0"+
    "\1\6\11\0\7\6\1\266\16\6\46\0\1\267\103\0"+
    "\1\205\56\0\1\237\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9338];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\3\1\1\11\10\1\1\11\1\1\1\11"+
    "\16\1\1\11\4\1\1\11\5\1\1\11\3\1\1\0"+
    "\1\1\1\0\5\1\2\11\3\1\4\0\13\1\1\11"+
    "\4\0\1\11\11\0\1\1\1\0\2\1\1\11\1\1"+
    "\1\11\1\1\4\0\13\1\15\0\2\1\2\0\1\11"+
    "\1\0\12\1\2\0\1\1\2\0\1\1\2\0\1\1"+
    "\1\0\2\1\3\0\6\1\7\0\2\1\3\0\2\1"+
    "\2\0\1\11\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public FMLTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * {@inheritDoc}
	 */
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "//", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

						case Token.COMMENT_DOCUMENTATION:
				state = DOCCOMMENT;
				start = text.offset;
				break;

			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new TokenImpl();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FMLTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FMLTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 26: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_DOCUMENTATION); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_DOCUMENTATION); start = zzMarkedPos;
          }
        case 29: break;
        case 3: 
          { addNullToken(); return firstToken;
          }
        case 30: break;
        case 15: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 31: break;
        case 5: 
          { addToken(Token.WHITESPACE);
          }
        case 32: break;
        case 20: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 33: break;
        case 21: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 34: break;
        case 16: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 35: break;
        case 19: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_DOCUMENTATION);
          }
        case 36: break;
        case 17: 
          { addToken(Token.RESERVED_WORD);
          }
        case 37: break;
        case 7: 
          { addToken(Token.SEPARATOR);
          }
        case 38: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 39: break;
        case 11: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 40: break;
        case 14: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 41: break;
        case 28: 
          { addToken(Token.FUNCTION);
          }
        case 42: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 43: break;
        case 23: 
          { addToken(Token.DATA_TYPE);
          }
        case 44: break;
        case 18: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 45: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_DOCUMENTATION); return firstToken;
          }
        case 46: break;
        case 22: 
          { start = zzMarkedPos-3; yybegin(DOCCOMMENT);
          }
        case 47: break;
        case 13: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 48: break;
        case 27: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 49: break;
        case 25: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 50: break;
        case 24: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 51: break;
        case 12: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 52: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 53: break;
        case 6: 
          { addToken(Token.OPERATOR);
          }
        case 54: break;
        case 8: 
          { 
          }
        case 55: break;
        case 9: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 56: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 184: break;
            case DOCCOMMENT: {
              yybegin(YYINITIAL); addToken(start,zzEndRead, Token.COMMENT_DOCUMENTATION); return firstToken;
            }
            case 185: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 186: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 187: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
