dependencies {
  // openflexo dep
  implementation group: 'junit', name: 'junit', version: '4.13.2'
  implementation project(':flexo-foundation')
  implementation project(':fml-cli')
  implementation project(':flexo-foundation-test')
  api project(':flexo-foundation-rm')
  // external dep

  // testing dep
  testImplementation project(':flexo-foundation-test')
  testImplementation project(':flexo-test-resources')
   
}
