rootProject.name = 'openflexo-core'

include 'flexo-test-resources',
        'flexo-foundation',
        'flexo-foundation-rm',
        'flexo-foundation-test',
        'flexo-documentation',
        'flexo-ontology',
        'fml-parser',
        'fml-cli',
        'fml-cli-test',
        'fml-lsp'
        