dependencies {
  // openflexo dep
  implementation flexoP2PP();
  implementation project(':flexo-foundation')
  // external dep

  // testing dep
 // testImplementation project(':flexo-foundation-test')
  testImplementation project(':flexo-test-resources')
}

apply plugin: 'sablecc'

def generateGrammarSourceTask = tasks.named("generateGrammarSource")

// We explicity declare a dependence between those two tasks
tasks.named("processResources") {
   dependsOn(generateGrammarSourceTask)
}

