/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AEnhancedForForStatement extends PForStatement
{
    private PEnhancedForStatement _enhancedForStatement_;

    public AEnhancedForForStatement()
    {
        // Constructor
    }

    public AEnhancedForForStatement(
        @SuppressWarnings("hiding") PEnhancedForStatement _enhancedForStatement_)
    {
        // Constructor
        setEnhancedForStatement(_enhancedForStatement_);

    }

    @Override
    public Object clone()
    {
        return new AEnhancedForForStatement(
            cloneNode(this._enhancedForStatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnhancedForForStatement(this);
    }

    public PEnhancedForStatement getEnhancedForStatement()
    {
        return this._enhancedForStatement_;
    }

    public void setEnhancedForStatement(PEnhancedForStatement node)
    {
        if(this._enhancedForStatement_ != null)
        {
            this._enhancedForStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enhancedForStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enhancedForStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enhancedForStatement_ == child)
        {
            this._enhancedForStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enhancedForStatement_ == oldChild)
        {
            setEnhancedForStatement((PEnhancedForStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
