/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AFinally extends PFinally
{
    private TFinallyToken _finallyToken_;
    private PBlock _block_;

    public AFinally()
    {
        // Constructor
    }

    public AFinally(
        @SuppressWarnings("hiding") TFinallyToken _finallyToken_,
        @SuppressWarnings("hiding") PBlock _block_)
    {
        // Constructor
        setFinallyToken(_finallyToken_);

        setBlock(_block_);

    }

    @Override
    public Object clone()
    {
        return new AFinally(
            cloneNode(this._finallyToken_),
            cloneNode(this._block_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFinally(this);
    }

    public TFinallyToken getFinallyToken()
    {
        return this._finallyToken_;
    }

    public void setFinallyToken(TFinallyToken node)
    {
        if(this._finallyToken_ != null)
        {
            this._finallyToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finallyToken_ = node;
    }

    public PBlock getBlock()
    {
        return this._block_;
    }

    public void setBlock(PBlock node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._finallyToken_)
            + toString(this._block_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._finallyToken_ == child)
        {
            this._finallyToken_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._finallyToken_ == oldChild)
        {
            setFinallyToken((TFinallyToken) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
