/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AFlexoBehaviourFlexoConceptMemberDeclaration extends PFlexoConceptMemberDeclaration
{
    private PFlexoBehaviourDeclaration _flexoBehaviourDeclaration_;

    public AFlexoBehaviourFlexoConceptMemberDeclaration()
    {
        // Constructor
    }

    public AFlexoBehaviourFlexoConceptMemberDeclaration(
        @SuppressWarnings("hiding") PFlexoBehaviourDeclaration _flexoBehaviourDeclaration_)
    {
        // Constructor
        setFlexoBehaviourDeclaration(_flexoBehaviourDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AFlexoBehaviourFlexoConceptMemberDeclaration(
            cloneNode(this._flexoBehaviourDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFlexoBehaviourFlexoConceptMemberDeclaration(this);
    }

    public PFlexoBehaviourDeclaration getFlexoBehaviourDeclaration()
    {
        return this._flexoBehaviourDeclaration_;
    }

    public void setFlexoBehaviourDeclaration(PFlexoBehaviourDeclaration node)
    {
        if(this._flexoBehaviourDeclaration_ != null)
        {
            this._flexoBehaviourDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._flexoBehaviourDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._flexoBehaviourDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._flexoBehaviourDeclaration_ == child)
        {
            this._flexoBehaviourDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._flexoBehaviourDeclaration_ == oldChild)
        {
            setFlexoBehaviourDeclaration((PFlexoBehaviourDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
