/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.*;
import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AIdentifierAssignment extends PAssignment
{
    private PLeftHandSide _leftHandSide_;
    private PAssignmentOperator _assignmentOperator_;
    private TIdentifier _identifier_;
    private final LinkedList<PAdditionalIdentifier> _additionalIdentifiers_ = new LinkedList<PAdditionalIdentifier>();

    public AIdentifierAssignment()
    {
        // Constructor
    }

    public AIdentifierAssignment(
        @SuppressWarnings("hiding") PLeftHandSide _leftHandSide_,
        @SuppressWarnings("hiding") PAssignmentOperator _assignmentOperator_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<PAdditionalIdentifier> _additionalIdentifiers_)
    {
        // Constructor
        setLeftHandSide(_leftHandSide_);

        setAssignmentOperator(_assignmentOperator_);

        setIdentifier(_identifier_);

        setAdditionalIdentifiers(_additionalIdentifiers_);

    }

    @Override
    public Object clone()
    {
        return new AIdentifierAssignment(
            cloneNode(this._leftHandSide_),
            cloneNode(this._assignmentOperator_),
            cloneNode(this._identifier_),
            cloneList(this._additionalIdentifiers_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentifierAssignment(this);
    }

    public PLeftHandSide getLeftHandSide()
    {
        return this._leftHandSide_;
    }

    public void setLeftHandSide(PLeftHandSide node)
    {
        if(this._leftHandSide_ != null)
        {
            this._leftHandSide_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftHandSide_ = node;
    }

    public PAssignmentOperator getAssignmentOperator()
    {
        return this._assignmentOperator_;
    }

    public void setAssignmentOperator(PAssignmentOperator node)
    {
        if(this._assignmentOperator_ != null)
        {
            this._assignmentOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignmentOperator_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PAdditionalIdentifier> getAdditionalIdentifiers()
    {
        return this._additionalIdentifiers_;
    }

    public void setAdditionalIdentifiers(List<PAdditionalIdentifier> list)
    {
        this._additionalIdentifiers_.clear();
        this._additionalIdentifiers_.addAll(list);
        for(PAdditionalIdentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftHandSide_)
            + toString(this._assignmentOperator_)
            + toString(this._identifier_)
            + toString(this._additionalIdentifiers_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftHandSide_ == child)
        {
            this._leftHandSide_ = null;
            return;
        }

        if(this._assignmentOperator_ == child)
        {
            this._assignmentOperator_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._additionalIdentifiers_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftHandSide_ == oldChild)
        {
            setLeftHandSide((PLeftHandSide) newChild);
            return;
        }

        if(this._assignmentOperator_ == oldChild)
        {
            setAssignmentOperator((PAssignmentOperator) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PAdditionalIdentifier> i = this._additionalIdentifiers_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
