/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.*;
import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AInitializerVariableDeclarator extends PVariableDeclarator
{
    private TIdentifier _identifier_;
    private final LinkedList<PDim> _dims_ = new LinkedList<PDim>();
    private TAssign _assign_;
    private PVariableInitializer _variableInitializer_;

    public AInitializerVariableDeclarator()
    {
        // Constructor
    }

    public AInitializerVariableDeclarator(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<PDim> _dims_,
        @SuppressWarnings("hiding") TAssign _assign_,
        @SuppressWarnings("hiding") PVariableInitializer _variableInitializer_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setDims(_dims_);

        setAssign(_assign_);

        setVariableInitializer(_variableInitializer_);

    }

    @Override
    public Object clone()
    {
        return new AInitializerVariableDeclarator(
            cloneNode(this._identifier_),
            cloneList(this._dims_),
            cloneNode(this._assign_),
            cloneNode(this._variableInitializer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitializerVariableDeclarator(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PDim> getDims()
    {
        return this._dims_;
    }

    public void setDims(List<PDim> list)
    {
        this._dims_.clear();
        this._dims_.addAll(list);
        for(PDim e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TAssign getAssign()
    {
        return this._assign_;
    }

    public void setAssign(TAssign node)
    {
        if(this._assign_ != null)
        {
            this._assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assign_ = node;
    }

    public PVariableInitializer getVariableInitializer()
    {
        return this._variableInitializer_;
    }

    public void setVariableInitializer(PVariableInitializer node)
    {
        if(this._variableInitializer_ != null)
        {
            this._variableInitializer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableInitializer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._dims_)
            + toString(this._assign_)
            + toString(this._variableInitializer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._dims_.remove(child))
        {
            return;
        }

        if(this._assign_ == child)
        {
            this._assign_ = null;
            return;
        }

        if(this._variableInitializer_ == child)
        {
            this._variableInitializer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PDim> i = this._dims_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDim) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        if(this._variableInitializer_ == oldChild)
        {
            setVariableInitializer((PVariableInitializer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
