/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class ALabeledStatementNoShortIfStatementNoShortIf extends PStatementNoShortIf
{
    private PLabeledStatementNoShortIf _labeledStatementNoShortIf_;

    public ALabeledStatementNoShortIfStatementNoShortIf()
    {
        // Constructor
    }

    public ALabeledStatementNoShortIfStatementNoShortIf(
        @SuppressWarnings("hiding") PLabeledStatementNoShortIf _labeledStatementNoShortIf_)
    {
        // Constructor
        setLabeledStatementNoShortIf(_labeledStatementNoShortIf_);

    }

    @Override
    public Object clone()
    {
        return new ALabeledStatementNoShortIfStatementNoShortIf(
            cloneNode(this._labeledStatementNoShortIf_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALabeledStatementNoShortIfStatementNoShortIf(this);
    }

    public PLabeledStatementNoShortIf getLabeledStatementNoShortIf()
    {
        return this._labeledStatementNoShortIf_;
    }

    public void setLabeledStatementNoShortIf(PLabeledStatementNoShortIf node)
    {
        if(this._labeledStatementNoShortIf_ != null)
        {
            this._labeledStatementNoShortIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._labeledStatementNoShortIf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._labeledStatementNoShortIf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._labeledStatementNoShortIf_ == child)
        {
            this._labeledStatementNoShortIf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._labeledStatementNoShortIf_ == oldChild)
        {
            setLabeledStatementNoShortIf((PLabeledStatementNoShortIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
