/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class ALtShShRelationalExpression extends PRelationalExpression
{
    private PShiftExpression _shiftExpression1_;
    private TLt _lt_;
    private PShiftExpression _shiftExpression2_;

    public ALtShShRelationalExpression()
    {
        // Constructor
    }

    public ALtShShRelationalExpression(
        @SuppressWarnings("hiding") PShiftExpression _shiftExpression1_,
        @SuppressWarnings("hiding") TLt _lt_,
        @SuppressWarnings("hiding") PShiftExpression _shiftExpression2_)
    {
        // Constructor
        setShiftExpression1(_shiftExpression1_);

        setLt(_lt_);

        setShiftExpression2(_shiftExpression2_);

    }

    @Override
    public Object clone()
    {
        return new ALtShShRelationalExpression(
            cloneNode(this._shiftExpression1_),
            cloneNode(this._lt_),
            cloneNode(this._shiftExpression2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtShShRelationalExpression(this);
    }

    public PShiftExpression getShiftExpression1()
    {
        return this._shiftExpression1_;
    }

    public void setShiftExpression1(PShiftExpression node)
    {
        if(this._shiftExpression1_ != null)
        {
            this._shiftExpression1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shiftExpression1_ = node;
    }

    public TLt getLt()
    {
        return this._lt_;
    }

    public void setLt(TLt node)
    {
        if(this._lt_ != null)
        {
            this._lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lt_ = node;
    }

    public PShiftExpression getShiftExpression2()
    {
        return this._shiftExpression2_;
    }

    public void setShiftExpression2(PShiftExpression node)
    {
        if(this._shiftExpression2_ != null)
        {
            this._shiftExpression2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shiftExpression2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._shiftExpression1_)
            + toString(this._lt_)
            + toString(this._shiftExpression2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._shiftExpression1_ == child)
        {
            this._shiftExpression1_ = null;
            return;
        }

        if(this._lt_ == child)
        {
            this._lt_ = null;
            return;
        }

        if(this._shiftExpression2_ == child)
        {
            this._shiftExpression2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._shiftExpression1_ == oldChild)
        {
            setShiftExpression1((PShiftExpression) newChild);
            return;
        }

        if(this._lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(this._shiftExpression2_ == oldChild)
        {
            setShiftExpression2((PShiftExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
