/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AManyActualTypeArgumentList extends PActualTypeArgumentList
{
    private PActualTypeArgumentList _actualTypeArgumentList_;
    private TComma _comma_;
    private PActualTypeArgument _actualTypeArgument_;

    public AManyActualTypeArgumentList()
    {
        // Constructor
    }

    public AManyActualTypeArgumentList(
        @SuppressWarnings("hiding") PActualTypeArgumentList _actualTypeArgumentList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PActualTypeArgument _actualTypeArgument_)
    {
        // Constructor
        setActualTypeArgumentList(_actualTypeArgumentList_);

        setComma(_comma_);

        setActualTypeArgument(_actualTypeArgument_);

    }

    @Override
    public Object clone()
    {
        return new AManyActualTypeArgumentList(
            cloneNode(this._actualTypeArgumentList_),
            cloneNode(this._comma_),
            cloneNode(this._actualTypeArgument_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyActualTypeArgumentList(this);
    }

    public PActualTypeArgumentList getActualTypeArgumentList()
    {
        return this._actualTypeArgumentList_;
    }

    public void setActualTypeArgumentList(PActualTypeArgumentList node)
    {
        if(this._actualTypeArgumentList_ != null)
        {
            this._actualTypeArgumentList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PActualTypeArgument getActualTypeArgument()
    {
        return this._actualTypeArgument_;
    }

    public void setActualTypeArgument(PActualTypeArgument node)
    {
        if(this._actualTypeArgument_ != null)
        {
            this._actualTypeArgument_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgument_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actualTypeArgumentList_)
            + toString(this._comma_)
            + toString(this._actualTypeArgument_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actualTypeArgumentList_ == child)
        {
            this._actualTypeArgumentList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._actualTypeArgument_ == child)
        {
            this._actualTypeArgument_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actualTypeArgumentList_ == oldChild)
        {
            setActualTypeArgumentList((PActualTypeArgumentList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._actualTypeArgument_ == oldChild)
        {
            setActualTypeArgument((PActualTypeArgument) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
