/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AManyActualTypeArgumentListUshr extends PActualTypeArgumentListUshr
{
    private PActualTypeArgumentList _actualTypeArgumentList_;
    private TComma _comma_;
    private PActualTypeArgumentUshr _actualTypeArgumentUshr_;

    public AManyActualTypeArgumentListUshr()
    {
        // Constructor
    }

    public AManyActualTypeArgumentListUshr(
        @SuppressWarnings("hiding") PActualTypeArgumentList _actualTypeArgumentList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PActualTypeArgumentUshr _actualTypeArgumentUshr_)
    {
        // Constructor
        setActualTypeArgumentList(_actualTypeArgumentList_);

        setComma(_comma_);

        setActualTypeArgumentUshr(_actualTypeArgumentUshr_);

    }

    @Override
    public Object clone()
    {
        return new AManyActualTypeArgumentListUshr(
            cloneNode(this._actualTypeArgumentList_),
            cloneNode(this._comma_),
            cloneNode(this._actualTypeArgumentUshr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyActualTypeArgumentListUshr(this);
    }

    public PActualTypeArgumentList getActualTypeArgumentList()
    {
        return this._actualTypeArgumentList_;
    }

    public void setActualTypeArgumentList(PActualTypeArgumentList node)
    {
        if(this._actualTypeArgumentList_ != null)
        {
            this._actualTypeArgumentList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PActualTypeArgumentUshr getActualTypeArgumentUshr()
    {
        return this._actualTypeArgumentUshr_;
    }

    public void setActualTypeArgumentUshr(PActualTypeArgumentUshr node)
    {
        if(this._actualTypeArgumentUshr_ != null)
        {
            this._actualTypeArgumentUshr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentUshr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actualTypeArgumentList_)
            + toString(this._comma_)
            + toString(this._actualTypeArgumentUshr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actualTypeArgumentList_ == child)
        {
            this._actualTypeArgumentList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._actualTypeArgumentUshr_ == child)
        {
            this._actualTypeArgumentUshr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actualTypeArgumentList_ == oldChild)
        {
            setActualTypeArgumentList((PActualTypeArgumentList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._actualTypeArgumentUshr_ == oldChild)
        {
            setActualTypeArgumentUshr((PActualTypeArgumentUshr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
