/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOneVariableInitializers extends PVariableInitializers
{
    private PVariableInitializer _variableInitializer_;

    public AOneVariableInitializers()
    {
        // Constructor
    }

    public AOneVariableInitializers(
        @SuppressWarnings("hiding") PVariableInitializer _variableInitializer_)
    {
        // Constructor
        setVariableInitializer(_variableInitializer_);

    }

    @Override
    public Object clone()
    {
        return new AOneVariableInitializers(
            cloneNode(this._variableInitializer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneVariableInitializers(this);
    }

    public PVariableInitializer getVariableInitializer()
    {
        return this._variableInitializer_;
    }

    public void setVariableInitializer(PVariableInitializer node)
    {
        if(this._variableInitializer_ != null)
        {
            this._variableInitializer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableInitializer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableInitializer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableInitializer_ == child)
        {
            this._variableInitializer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variableInitializer_ == oldChild)
        {
            setVariableInitializer((PVariableInitializer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
