/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOneActualTypeArgumentListShr extends PActualTypeArgumentListShr
{
    private PActualTypeArgumentShr _actualTypeArgumentShr_;

    public AOneActualTypeArgumentListShr()
    {
        // Constructor
    }

    public AOneActualTypeArgumentListShr(
        @SuppressWarnings("hiding") PActualTypeArgumentShr _actualTypeArgumentShr_)
    {
        // Constructor
        setActualTypeArgumentShr(_actualTypeArgumentShr_);

    }

    @Override
    public Object clone()
    {
        return new AOneActualTypeArgumentListShr(
            cloneNode(this._actualTypeArgumentShr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneActualTypeArgumentListShr(this);
    }

    public PActualTypeArgumentShr getActualTypeArgumentShr()
    {
        return this._actualTypeArgumentShr_;
    }

    public void setActualTypeArgumentShr(PActualTypeArgumentShr node)
    {
        if(this._actualTypeArgumentShr_ != null)
        {
            this._actualTypeArgumentShr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentShr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actualTypeArgumentShr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actualTypeArgumentShr_ == child)
        {
            this._actualTypeArgumentShr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actualTypeArgumentShr_ == oldChild)
        {
            setActualTypeArgumentShr((PActualTypeArgumentShr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
