/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOneElementValuePairs extends PElementValuePairs
{
    private PElementValuePair _elementValuePair_;

    public AOneElementValuePairs()
    {
        // Constructor
    }

    public AOneElementValuePairs(
        @SuppressWarnings("hiding") PElementValuePair _elementValuePair_)
    {
        // Constructor
        setElementValuePair(_elementValuePair_);

    }

    @Override
    public Object clone()
    {
        return new AOneElementValuePairs(
            cloneNode(this._elementValuePair_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneElementValuePairs(this);
    }

    public PElementValuePair getElementValuePair()
    {
        return this._elementValuePair_;
    }

    public void setElementValuePair(PElementValuePair node)
    {
        if(this._elementValuePair_ != null)
        {
            this._elementValuePair_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementValuePair_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementValuePair_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementValuePair_ == child)
        {
            this._elementValuePair_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementValuePair_ == oldChild)
        {
            setElementValuePair((PElementValuePair) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
