/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class APostDecrementStatementExpression extends PStatementExpression
{
    private PPostDecrementExpression _postDecrementExpression_;

    public APostDecrementStatementExpression()
    {
        // Constructor
    }

    public APostDecrementStatementExpression(
        @SuppressWarnings("hiding") PPostDecrementExpression _postDecrementExpression_)
    {
        // Constructor
        setPostDecrementExpression(_postDecrementExpression_);

    }

    @Override
    public Object clone()
    {
        return new APostDecrementStatementExpression(
            cloneNode(this._postDecrementExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostDecrementStatementExpression(this);
    }

    public PPostDecrementExpression getPostDecrementExpression()
    {
        return this._postDecrementExpression_;
    }

    public void setPostDecrementExpression(PPostDecrementExpression node)
    {
        if(this._postDecrementExpression_ != null)
        {
            this._postDecrementExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postDecrementExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._postDecrementExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._postDecrementExpression_ == child)
        {
            this._postDecrementExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._postDecrementExpression_ == oldChild)
        {
            setPostDecrementExpression((PPostDecrementExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
