/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.*;
import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class APrimitiveArrayCreationExpression extends PArrayCreationExpression
{
    private TNew _new_;
    private PPrimitiveType _primitiveType_;
    private final LinkedList<PDimExpr> _dimExprs_ = new LinkedList<PDimExpr>();
    private final LinkedList<PDim> _dims_ = new LinkedList<PDim>();

    public APrimitiveArrayCreationExpression()
    {
        // Constructor
    }

    public APrimitiveArrayCreationExpression(
        @SuppressWarnings("hiding") TNew _new_,
        @SuppressWarnings("hiding") PPrimitiveType _primitiveType_,
        @SuppressWarnings("hiding") List<PDimExpr> _dimExprs_,
        @SuppressWarnings("hiding") List<PDim> _dims_)
    {
        // Constructor
        setNew(_new_);

        setPrimitiveType(_primitiveType_);

        setDimExprs(_dimExprs_);

        setDims(_dims_);

    }

    @Override
    public Object clone()
    {
        return new APrimitiveArrayCreationExpression(
            cloneNode(this._new_),
            cloneNode(this._primitiveType_),
            cloneList(this._dimExprs_),
            cloneList(this._dims_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimitiveArrayCreationExpression(this);
    }

    public TNew getNew()
    {
        return this._new_;
    }

    public void setNew(TNew node)
    {
        if(this._new_ != null)
        {
            this._new_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._new_ = node;
    }

    public PPrimitiveType getPrimitiveType()
    {
        return this._primitiveType_;
    }

    public void setPrimitiveType(PPrimitiveType node)
    {
        if(this._primitiveType_ != null)
        {
            this._primitiveType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primitiveType_ = node;
    }

    public LinkedList<PDimExpr> getDimExprs()
    {
        return this._dimExprs_;
    }

    public void setDimExprs(List<PDimExpr> list)
    {
        this._dimExprs_.clear();
        this._dimExprs_.addAll(list);
        for(PDimExpr e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public LinkedList<PDim> getDims()
    {
        return this._dims_;
    }

    public void setDims(List<PDim> list)
    {
        this._dims_.clear();
        this._dims_.addAll(list);
        for(PDim e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._new_)
            + toString(this._primitiveType_)
            + toString(this._dimExprs_)
            + toString(this._dims_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._new_ == child)
        {
            this._new_ = null;
            return;
        }

        if(this._primitiveType_ == child)
        {
            this._primitiveType_ = null;
            return;
        }

        if(this._dimExprs_.remove(child))
        {
            return;
        }

        if(this._dims_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._new_ == oldChild)
        {
            setNew((TNew) newChild);
            return;
        }

        if(this._primitiveType_ == oldChild)
        {
            setPrimitiveType((PPrimitiveType) newChild);
            return;
        }

        for(ListIterator<PDimExpr> i = this._dimExprs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDimExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PDim> i = this._dims_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDim) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
