/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AShrTypeParameters extends PTypeParameters
{
    private TLt _lt_;
    private PTypeParameterListShr _typeParameterListShr_;
    private TShr _shr_;

    public AShrTypeParameters()
    {
        // Constructor
    }

    public AShrTypeParameters(
        @SuppressWarnings("hiding") TLt _lt_,
        @SuppressWarnings("hiding") PTypeParameterListShr _typeParameterListShr_,
        @SuppressWarnings("hiding") TShr _shr_)
    {
        // Constructor
        setLt(_lt_);

        setTypeParameterListShr(_typeParameterListShr_);

        setShr(_shr_);

    }

    @Override
    public Object clone()
    {
        return new AShrTypeParameters(
            cloneNode(this._lt_),
            cloneNode(this._typeParameterListShr_),
            cloneNode(this._shr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShrTypeParameters(this);
    }

    public TLt getLt()
    {
        return this._lt_;
    }

    public void setLt(TLt node)
    {
        if(this._lt_ != null)
        {
            this._lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lt_ = node;
    }

    public PTypeParameterListShr getTypeParameterListShr()
    {
        return this._typeParameterListShr_;
    }

    public void setTypeParameterListShr(PTypeParameterListShr node)
    {
        if(this._typeParameterListShr_ != null)
        {
            this._typeParameterListShr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeParameterListShr_ = node;
    }

    public TShr getShr()
    {
        return this._shr_;
    }

    public void setShr(TShr node)
    {
        if(this._shr_ != null)
        {
            this._shr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lt_)
            + toString(this._typeParameterListShr_)
            + toString(this._shr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lt_ == child)
        {
            this._lt_ = null;
            return;
        }

        if(this._typeParameterListShr_ == child)
        {
            this._typeParameterListShr_ = null;
            return;
        }

        if(this._shr_ == child)
        {
            this._shr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(this._typeParameterListShr_ == oldChild)
        {
            setTypeParameterListShr((PTypeParameterListShr) newChild);
            return;
        }

        if(this._shr_ == oldChild)
        {
            setShr((TShr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
