/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleConditionalAndExpression extends PConditionalAndExpression
{
    private PInclusiveOrExpression _inclusiveOrExpression_;

    public ASimpleConditionalAndExpression()
    {
        // Constructor
    }

    public ASimpleConditionalAndExpression(
        @SuppressWarnings("hiding") PInclusiveOrExpression _inclusiveOrExpression_)
    {
        // Constructor
        setInclusiveOrExpression(_inclusiveOrExpression_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleConditionalAndExpression(
            cloneNode(this._inclusiveOrExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleConditionalAndExpression(this);
    }

    public PInclusiveOrExpression getInclusiveOrExpression()
    {
        return this._inclusiveOrExpression_;
    }

    public void setInclusiveOrExpression(PInclusiveOrExpression node)
    {
        if(this._inclusiveOrExpression_ != null)
        {
            this._inclusiveOrExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inclusiveOrExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inclusiveOrExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inclusiveOrExpression_ == child)
        {
            this._inclusiveOrExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inclusiveOrExpression_ == oldChild)
        {
            setInclusiveOrExpression((PInclusiveOrExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
