/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AThrowStatementStatementWithoutTrailingSubstatement extends PStatementWithoutTrailingSubstatement
{
    private PThrowStatement _throwStatement_;

    public AThrowStatementStatementWithoutTrailingSubstatement()
    {
        // Constructor
    }

    public AThrowStatementStatementWithoutTrailingSubstatement(
        @SuppressWarnings("hiding") PThrowStatement _throwStatement_)
    {
        // Constructor
        setThrowStatement(_throwStatement_);

    }

    @Override
    public Object clone()
    {
        return new AThrowStatementStatementWithoutTrailingSubstatement(
            cloneNode(this._throwStatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThrowStatementStatementWithoutTrailingSubstatement(this);
    }

    public PThrowStatement getThrowStatement()
    {
        return this._throwStatement_;
    }

    public void setThrowStatement(PThrowStatement node)
    {
        if(this._throwStatement_ != null)
        {
            this._throwStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._throwStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._throwStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._throwStatement_ == child)
        {
            this._throwStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._throwStatement_ == oldChild)
        {
            setThrowStatement((PThrowStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
