/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class ATypeArgumentsShrNoGt extends PTypeArgumentsShrNoGt
{
    private TLt _lt_;
    private PActualTypeArgumentList _actualTypeArgumentList_;

    public ATypeArgumentsShrNoGt()
    {
        // Constructor
    }

    public ATypeArgumentsShrNoGt(
        @SuppressWarnings("hiding") TLt _lt_,
        @SuppressWarnings("hiding") PActualTypeArgumentList _actualTypeArgumentList_)
    {
        // Constructor
        setLt(_lt_);

        setActualTypeArgumentList(_actualTypeArgumentList_);

    }

    @Override
    public Object clone()
    {
        return new ATypeArgumentsShrNoGt(
            cloneNode(this._lt_),
            cloneNode(this._actualTypeArgumentList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeArgumentsShrNoGt(this);
    }

    public TLt getLt()
    {
        return this._lt_;
    }

    public void setLt(TLt node)
    {
        if(this._lt_ != null)
        {
            this._lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lt_ = node;
    }

    public PActualTypeArgumentList getActualTypeArgumentList()
    {
        return this._actualTypeArgumentList_;
    }

    public void setActualTypeArgumentList(PActualTypeArgumentList node)
    {
        if(this._actualTypeArgumentList_ != null)
        {
            this._actualTypeArgumentList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lt_)
            + toString(this._actualTypeArgumentList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lt_ == child)
        {
            this._lt_ = null;
            return;
        }

        if(this._actualTypeArgumentList_ == child)
        {
            this._actualTypeArgumentList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(this._actualTypeArgumentList_ == oldChild)
        {
            setActualTypeArgumentList((PActualTypeArgumentList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
