/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AVoidPrimaryNoNewArray extends PPrimaryNoNewArray
{
    private TVoid _void_;
    private TDot _dot_;
    private TClassToken _classToken_;

    public AVoidPrimaryNoNewArray()
    {
        // Constructor
    }

    public AVoidPrimaryNoNewArray(
        @SuppressWarnings("hiding") TVoid _void_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TClassToken _classToken_)
    {
        // Constructor
        setVoid(_void_);

        setDot(_dot_);

        setClassToken(_classToken_);

    }

    @Override
    public Object clone()
    {
        return new AVoidPrimaryNoNewArray(
            cloneNode(this._void_),
            cloneNode(this._dot_),
            cloneNode(this._classToken_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidPrimaryNoNewArray(this);
    }

    public TVoid getVoid()
    {
        return this._void_;
    }

    public void setVoid(TVoid node)
    {
        if(this._void_ != null)
        {
            this._void_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._void_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TClassToken getClassToken()
    {
        return this._classToken_;
    }

    public void setClassToken(TClassToken node)
    {
        if(this._classToken_ != null)
        {
            this._classToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._void_)
            + toString(this._dot_)
            + toString(this._classToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._void_ == child)
        {
            this._void_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._classToken_ == child)
        {
            this._classToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._void_ == oldChild)
        {
            setVoid((TVoid) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._classToken_ == oldChild)
        {
            setClassToken((TClassToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
