/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class AWildcardUshr extends PWildcardUshr
{
    private TQmark _qmark_;
    private PWildcardBoundsUshr _wildcardBoundsUshr_;

    public AWildcardUshr()
    {
        // Constructor
    }

    public AWildcardUshr(
        @SuppressWarnings("hiding") TQmark _qmark_,
        @SuppressWarnings("hiding") PWildcardBoundsUshr _wildcardBoundsUshr_)
    {
        // Constructor
        setQmark(_qmark_);

        setWildcardBoundsUshr(_wildcardBoundsUshr_);

    }

    @Override
    public Object clone()
    {
        return new AWildcardUshr(
            cloneNode(this._qmark_),
            cloneNode(this._wildcardBoundsUshr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWildcardUshr(this);
    }

    public TQmark getQmark()
    {
        return this._qmark_;
    }

    public void setQmark(TQmark node)
    {
        if(this._qmark_ != null)
        {
            this._qmark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qmark_ = node;
    }

    public PWildcardBoundsUshr getWildcardBoundsUshr()
    {
        return this._wildcardBoundsUshr_;
    }

    public void setWildcardBoundsUshr(PWildcardBoundsUshr node)
    {
        if(this._wildcardBoundsUshr_ != null)
        {
            this._wildcardBoundsUshr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._wildcardBoundsUshr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._qmark_)
            + toString(this._wildcardBoundsUshr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._qmark_ == child)
        {
            this._qmark_ = null;
            return;
        }

        if(this._wildcardBoundsUshr_ == child)
        {
            this._wildcardBoundsUshr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._qmark_ == oldChild)
        {
            setQmark((TQmark) newChild);
            return;
        }

        if(this._wildcardBoundsUshr_ == oldChild)
        {
            setWildcardBoundsUshr((PWildcardBoundsUshr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
