/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

public abstract class PActualTypeArgumentUshrNoGt extends Node
{
    // Empty body
}
