/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class TFinallyToken extends Token
{
    public TFinallyToken()
    {
        super.setText("finally");
    }

    public TFinallyToken(int line, int pos)
    {
        super.setText("finally");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFinallyToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFinallyToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFinallyToken text.");
    }
}
