/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class TNative extends Token
{
    public TNative()
    {
        super.setText("native");
    }

    public TNative(int line, int pos)
    {
        super.setText("native");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNative(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNative(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNative text.");
    }
}
