/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.*;

@SuppressWarnings("nls")
public final class TSynchronized extends Token
{
    public TSynchronized()
    {
        super.setText("synchronized");
    }

    public TSynchronized(int line, int pos)
    {
        super.setText("synchronized");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSynchronized(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSynchronized(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSynchronized text.");
    }
}
